name: Build
on:
  repository_dispatch:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: panekj/manx
          ref: ${{ github.ref }}
          token: ${{ secrets.REPO_TOKEN }}
          submodules: recursive
      - name: Build app
        uses: crazy-max/ghaction-xgo@v1.5.0
        with:
          v: true
          targets: windows/*,linux/*,darwin/*
          ldflags: '-X "github.com/panekj/manx/cmd.Version=${{ github.sha }}"'
      - name: Upload release to GitHub
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          file: '/home/runner/work/manx-project/manx-project/build/github.com/panekj/*'
          draft: false
          tags: false
          verbose: true
          update_latest_release: true
